name: ci-master

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    name: CI Prod
    outputs:
      version: ${{ steps.read_version.outputs.VERSION }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v4

      - name: read version file
        id: read_version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: bump version
        id: bump
        uses: cbrgm/semver-bump-action@main
        with:
          current-version: ${{steps.read_version.outputs.VERSION}}
          bump-level: patch

      - name: write version file
        run: echo "${{ steps.bump.outputs.new_version }}" > VERSION

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/bcommonslab/commonkno:latest,ghcr.io/bcommonslab/commonkno:${{ steps.bump.outputs.new_version }}
          build-args: |
            NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
            CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}
            NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
            NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
            NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/
            NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/
          secrets: |
            "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}"
            "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}"
            
      - name: Push version and tag
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add VERSION
          git commit -m "Bump version to ${{ steps.bump.outputs.new_version }} [skip ci]"
          git tag -a -m "${{ steps.bump.outputs.new_version }}" v${{ steps.bump.outputs.new_version }}
          git push --follow-tags
          
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          generate_release_notes: true
          tag_name: v${{ steps.bump.outputs.new_version }}
      # This currently does not work, because dokploy will not pull the latest image, manually change the tag in dokploy. 
      - name: Trigger deployment
        run: curl -X GET https://dokploy.bcommonslab.org/api/deploy/compose/evw5skg-YMLsoiJx17t-m


